//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flat()
        {
            this.Request = new HashSet<Request>();
        }
    
        public int IdFlat { get; set; }
        public int BuildingNumberOfRoom { get; set; }
        public decimal Price { get; set; }
        public int NumberOfRooms { get; set; }
        public int Area { get; set; }
        public int FloorNumber { get; set; }
        public int EntanceNumber { get; set; }
        public int IdSkyscraper { get; set; }
        public string ImagePreview { get; set; }
    
        public virtual Skyscraper Skyscraper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Request { get; set; }
    }
}
