//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateAgency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Flat = new HashSet<Flat>();
        }
    
        public int IdRequset { get; set; }
        public Nullable<decimal> MinimumPrice { get; set; }
        public decimal MaximumPrice { get; set; }
        public int NumberOfRooms { get; set; }
        public int MinimumArea { get; set; }
        public Nullable<int> MaximumArea { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int IdDistrict { get; set; }
        public int IdEmployee { get; set; }
        public int IdClient { get; set; }
        public int IdRequestStatus { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual District District { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flat> Flat { get; set; }
    }
}
